### ISSUE TITLE
Choosing a username for playing anonymously

### ISSUE THREAD

**Issue by fgubler** [JordanPawlett/cards-against-formality#2]
Is it possible that the usernames chosen for playing anonymously stay blocked "forever"?
Maybe something like a timeout would be useful (like either until the end of the session or for 24h or something like that)...

**Comment by fgubler** [comment]
Also, if the username is already taken, there seems to be no nice error-message explaining the problem (it just doesn't proceed).

**Comment by JordanPawlett** [comment]
Hello, thank you for creating this issue!

Anonymous users will remain active, unless they do not visit the website for a few days. At this point the user is removed, along with the username. Freeing it up for use again!
If you play as an anonymous user, and come back to the site shortly, it should log you back in as the same user.

Unfortunately to reserver a permanent username, you need to login via Google or Facebook.

Regarding the second issue you mentioned. There is definitely supposed to be an error message displayed if you enter a already taken username. A check to see if the username exists is made as you type!
I'll fix this now, not sure how its disappeared.

Thank you

**Comment by JordanPawlett** [comment]
Fixed the bug regarding the 'username already exists" error not being displayed correctly.

**Comment by Der-Flip** [comment]
four years on an I feel like anonymous usernames are still not cleared out. I created three anonymous names. between each creation there was more than a week, mostly 2, yet I was forced to pick a new name. and now three names are blocked....
